# Generated by Django 2.2.6 on 2019-10-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20191029_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
