# Generated by Django 2.2.5 on 2019-10-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20191030_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('Technical', 'Technical'), ('Non-Technical', 'Non-Technical'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
