# Generated by Django 2.2.6 on 2019-10-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20191031_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='timespent1',
            field=models.TimeField(null=True),
        ),
    ]
