# Generated by Django 2.2.6 on 2019-11-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20191031_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='timespent1',
            field=models.TextField(),
        ),
    ]
