# Generated by Django 2.2.6 on 2019-11-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_responses_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='user',
        ),
    ]
