# Generated by Django 2.2.6 on 2019-11-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_responses_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='timespent2',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='responses',
            name='timespent1',
            field=models.TextField(default=0),
        ),
    ]
