# Generated by Django 2.2.6 on 2019-11-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20191101_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='question4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='responses',
            name='question5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='responses',
            name='question6',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='responses',
            name='question7',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='responses',
            name='question8',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='responses',
            name='question9',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='responses',
            name='timespent3',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='responses',
            name='timespent4',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='responses',
            name='timespent5',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='responses',
            name='timespent6',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='responses',
            name='timespent7',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='responses',
            name='timespent8',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='responses',
            name='timespent9',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='responses',
            name='question1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='responses',
            name='question2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='responses',
            name='question3',
            field=models.TextField(default=''),
        ),
    ]
