# Generated by Django 2.2.6 on 2019-11-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20191101_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctor',
            name='email_id',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='exp',
            field=models.IntegerField(choices=[('0', '0'), ('2+', '2+'), ('5+', '5+'), ('10+', '10+')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_no',
            field=models.IntegerField(unique=True),
        ),
    ]
