# Generated by Django 2.2.5 on 2019-11-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_auto_20191103_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses1',
            name='username',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='responses2',
            name='username',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='responses3',
            name='username',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='responses4',
            name='username',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='responses5',
            name='username',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='responses6',
            name='username',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='responses7',
            name='username',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='responses8',
            name='username',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='responses9',
            name='username',
            field=models.TextField(default=''),
        ),
    ]
